name: carbuterra
description: "Calculer les coûts, distances et émissions de CO2 liés à la consommation de carburant."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/earthEurope.svg
    - assets/euro.svg
    - assets/fuel.svg
    - assets/route.svg
